version: '3'

vars:
#  GIT_COMMIT:
#    sh: git log -n 1 --format=%h

  GOOS: linux

env:
  CGO_ENABLED: '0'

tasks:
  default:
    cmds:
      - task: test

  mod:
    desc: Init and tidy Go modules
    cmds:
      - go mod init
      - go mod tidy

  lint:
    desc: Runs golint
    cmds:
      - golangci-lint run
    silent: true

  test:
    desc: Runs test suite
    cmds:
      - go test {{catLines .GO_PACKAGES}}

  test-release:
    desc: Tests release process without publishing
    cmds:
      - goreleaser --snapshot --rm-dist

  release:
    desc: Release with goreleaser
    cmds:
      - goreleaser release --rm-dist

  build:
    desc: Build nodestatc
    cmds:
      - go build -v -ldflags="-w -s -X main.commit={{.GIT_COMMIT}}" -o bin/nodestat ./cmd/main.go

  clean:
    desc: Cleans temp files and folders
    cmds:
      - rm -rf dist/*